version: '3.3'

services:
  mongo:
    image: mongo
    container_name: taskforge-mongo
    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskforge-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskforge
    depends_on:
      - mongo 